Discord:
  url: "&3Equestrians United discord is https://discord.gg/BENtZpB"
Instagram:
  url: "&3Equestrians United Instagram is https://www.instagram.com/equestrians.united.mc/?hl=en"
YouTube:
  url: "&3Equestrians United YouTube is https://www.youtube.com/channel/UCnEzzOx3zHf29RHGPghYkuw"